
services:
  postgres:
    image: postgres:15
    container_name: email-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emaildb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres-data: