
services:
  postgres:
    image: postgres:15
    container_name: product-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # 

volumes:
  postgres-data: